var mid2TFQuestion = {
    q1:{
      description : 'High associativity in a cache reduces compulsory misses',
      result: 'F',
      answer: 'unknown',
      activeColor: 'black',
    },
    q2:{
      description : 'For a given capacity and block size, a set-associative cache implementation will typically have a lower hit time than a direct-mapped implementation.',
      result: 'F',
      answer: 'unknown',
      activeColor: 'black',
    },
    q3:{
      description : 'SRAMs are optimized for storage density.',
      result: 'F',
      answer: 'unknown',
      activeColor: 'black',
    },
    q4:{
      description : 'TLBs are placed on a special cache memory.',
      result: 'T',
      answer: 'unknown',
      activeColor: 'black',
    },
    q5:{
      description : 'SIMD architectures exploits instruction-level parallelism.',
      result: 'F',
      answer: 'unknown',
      activeColor: 'black',
    },
    q6:{
      description : 'Processors with lower CPIs will always be faster.',
      result: 'F',
      answer: 'unknown',
      activeColor: 'black',
    },
    q7:{
      description : 'Parallelism at data level means parallel execution of multiple instructions of the same type.',
      result: 'T',
      answer: 'unknown',
      activeColor: 'black',
    },
    q8:{
      description : 'Designating a preferred thread sacrifices throughput.',
      result: 'T',
      answer: 'unknown',
      activeColor: 'black',
    },
    q9:{
      description : 'Amdahl’s Law doesn’t apply to parallel computers',
      result: 'F',
      answer: 'unknown',
      activeColor: 'black',
    },
    q10:{
      description : 'Data-level parallelism achieved by performing the same operation on independent data',
      result: 'T',
      answer: 'unknown',
      activeColor: 'black',
    },
    q11:{
      description : 'A Shared Address Space programming model can be used on large scale multiprocessors.',
      result: 'T',
      answer: 'unknown',
      activeColor: 'black',
    },
    q12:{
      description : 'Clusters have separate memories and thus need many copies of the operating system.',
      result: 'T',
      answer: 'unknown',
      activeColor: 'black',
    },
    q13:{
      description : 'Name dependencies are detected at runtime in superscalar processors.',
      result: 'T',
      answer: 'unknown',
      activeColor: 'black',
    },
    q14:{
      description : 'Loops with no loop-carried dependencies can be executed in parallel.',
      result: 'T',
      answer: 'unknown',
      activeColor: 'black',
    },
    q15:{
      description : 'Amdahl\'s law does not apply to GPUs.',
      result: 'F',
      answer: 'unknown',
      activeColor: 'black',
    },
    q16:{
      description : 'Multimedia extensions can be thought of as a vector architecture with short vectors that support only contiguous vector data transfers.',
      result: 'T',
      answer: 'unknown',
      activeColor: 'black',
    },
    q17:{
      description : 'VLIW architectures execute instructions in parallel based on a fixed schedule determined when the code is compiled.',
      result: 'T',
      answer: 'unknown',
      activeColor: 'black',
    },
    q18:{
      description : 'Dynamic scheduling cannot handle dependencies that are not known at compile time.',
      result: 'F',
      answer: 'unknown',
      activeColor: 'black',
    },
    q19:{
      description : 'Wider instruction issues would decrease CPI cycles per instruction.',
      result: 'T',
      answer: 'unknown',
      activeColor: 'black',
    },
}